[
    {
        "cve": "CVE-2022-41343",
        "poc_github": true,
        "full_name": "BKreisel/CVE-2022-41343",
        "owner_login": "BKreisel",
        "owner_id": 1513073,
        "owner_html_url": "https://github.com/BKreisel",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/1513073?v=4",
        "html_url": "https://github.com/BKreisel/CVE-2022-41343",
        "description": "\ud83d\udc0d Python Exploit for CVE-2022-23935",
        "fork": false,
        "created_at": "2023-02-15T23:17:55Z",
        "updated_at": "2024-01-17T19:11:33Z",
        "pushed_at": "2023-02-17T18:37:12Z",
        "stargazers_count": 3,
        "watchers_count": 3,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "['cve', 'cve-2022-41343', 'exploit', 'python']",
        "visibility": "public",
        "forks": 0,
        "watchers": 3,
        "score": 0,
        "subscribers_count": 1
    }
]