[
    {
        "cve": "CVE-2011-3556",
        "poc_github": true,
        "full_name": "sk4la/cve_2011_3556",
        "owner_login": "sk4la",
        "owner_id": 38187780,
        "owner_html_url": "https://github.com/sk4la",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/38187780?v=4",
        "html_url": "https://github.com/sk4la/cve_2011_3556",
        "description": "Python 3 implementation of an existing CVE-2011-3556 proof of concept (PoC).",
        "fork": false,
        "created_at": "2019-01-29T20:22:09Z",
        "updated_at": "2025-01-18T17:13:35Z",
        "pushed_at": "2019-01-29T20:26:24Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "['cve-2011-3556', 'exploit', 'java', 'python', 'python3', 'vulnerability-assessment']",
        "visibility": "public",
        "forks": 0,
        "watchers": 1,
        "score": 0,
        "subscribers_count": 2
    }
]