[
    {
        "cve": "CVE-2024-25641",
        "poc_github": true,
        "full_name": "XiaomingX/cve-2024-25641-poc",
        "owner_login": "XiaomingX",
        "owner_id": 5387930,
        "owner_html_url": "https://github.com/XiaomingX",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/5387930?v=4",
        "html_url": "https://github.com/XiaomingX/cve-2024-25641-poc",
        "description": "PoC for CVE-2024-25641 Authenticated RCE on Cacti v1.2.26",
        "fork": false,
        "created_at": "2024-11-22T14:05:37Z",
        "updated_at": "2025-01-13T18:17:48Z",
        "pushed_at": "2024-11-22T14:09:15Z",
        "stargazers_count": 3,
        "watchers_count": 3,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 0,
        "watchers": 3,
        "score": 0,
        "subscribers_count": 1
    },
    {
        "cve": "CVE-2024-25641",
        "poc_github": true,
        "full_name": "D3Ext/CVE-2024-25641",
        "owner_login": "D3Ext",
        "owner_id": 67125397,
        "owner_html_url": "https://github.com/D3Ext",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/67125397?v=4",
        "html_url": "https://github.com/D3Ext/CVE-2024-25641",
        "description": "POC exploit for CVE-2024-25641",
        "fork": false,
        "created_at": "2025-01-05T21:33:18Z",
        "updated_at": "2025-08-11T15:02:36Z",
        "pushed_at": "2025-01-06T18:50:17Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "['cve-2024-25641', 'python']",
        "visibility": "public",
        "forks": 0,
        "watchers": 1,
        "score": 0,
        "subscribers_count": 1
    }
]