[
    {
        "cve": "CVE-2024-24549",
        "poc_github": true,
        "full_name": "JFOZ1010/CVE-2024-24549",
        "owner_login": "JFOZ1010",
        "owner_id": 82562585,
        "owner_html_url": "https://github.com/JFOZ1010",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/82562585?v=4",
        "html_url": "https://github.com/JFOZ1010/CVE-2024-24549",
        "description": "Proof of concept of the CVE-2024-24549, Exploit in Python. ",
        "fork": false,
        "created_at": "2024-12-09T04:59:07Z",
        "updated_at": "2025-01-13T01:24:19Z",
        "pushed_at": "2024-12-16T23:48:12Z",
        "stargazers_count": 6,
        "watchers_count": 6,
        "has_discussions": false,
        "forks_count": 3,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 3,
        "watchers": 6,
        "score": 0,
        "subscribers_count": 1
    }
]